#ifndef __BOARD_H__
#define __BOARD_H__

/* ´®¿Ú(radioLink) */
#define SERIAL_UART2_PORT_CLK   (RCC_AHB1Periph_GPIOA)
#define SERIAL_UART2_RX_PORT	GPIOA
#define SERIAL_UART2_RX_PIN	GPIO_Pin_3
#define SERIAL_UART2_TX_PORT	GPIOA
#define SERIAL_UART2_TX_PIN	GPIO_Pin_2

//#define SERIAL_UART2_CTS_PIN	GPIO_Pin_3
//#define SERIAL_UART2_RTS_PIN	GPIO_Pin_4

#define SERIAL_UART2_RX_DMA_STREAM  DMA1_Stream5
#define SERIAL_UART2_RX_DMA_CH	DMA_Channel_4
#define SERIAL_UART2_TX_DMA_STREAM  DMA1_Stream6
#define SERIAL_UART2_TX_DMA_CH	DMA_Channel_4

#define SERIAL_UART2_TX_DMA_IT	DMA1_Stream6_IRQHandler
#define SERIAL_UART2_TX_IRQn	USART2_IRQHandler

#define SERIAL_UART2_RX_TC_FLAG	DMA1_FLAG_TC6
#define SERIAL_UART2_RX_HT_FLAG	DMA1_FLAG_HT6
#define SERIAL_UART2_RX_TE_FLAG	DMA1_FLAG_TE6
#define SERIAL_UART2_RX_GL_FLAG	DMA1_FLAG_GL6
#define SERIAL_UART2_TX_TC_FLAG	DMA1_FLAG_TC7
#define SERIAL_UART2_TX_HT_FLAG	DMA1_FLAG_HT7
#define SERIAL_UART2_TX_TE_FLAG	DMA1_FLAG_TE7
#define SERIAL_UART2_TX_GL_FLAG	DMA1_FLAG_GL7









#if (defined SERIAL_UART1_TX_PORT) || (defined SERIAL_UART1_RX_PORT)
#define SERIAL_UART1_PORT
#endif

#if (defined SERIAL_UART2_TX_PORT) || (defined SERIAL_UART2_RX_PORT)
#define SERIAL_UART2_PORT
#endif

#if (defined SERIAL_UART3_TX_PORT) || (defined SERIAL_UART3_RX_PORT)
#define SERIAL_UART3_PORT
#endif

#if (defined SERIAL_UART4_TX_PORT) || (defined SERIAL_UART4_RX_PORT)
#define SERIAL_UART4_PORT
#endif

#if (defined SERIAL_UART5_TX_PORT) || (defined SERIAL_UART5_RX_PORT)
#define SERIAL_UART5_PORT
#endif
#endif

